### ISSUE TITLE
After :PluginInstall lornix/vim-scrollbar ; scrollbar is shown however is not possible to move

### ISSUE THREAD

**Issue by serup** [lornix/vim-scrollbar#8]
I tried installing your plugin in vim 7.4, and it shows the scrollbar in leftside, when I press < leader >sb 
however it is not possible for me to use mouse to scroll down or up -- what could be the issue??

**Comment by lornix** [comment]
Did your mouse scroll down or up BEFORE you installed the plugin? Basic Troubleshooting.

**Comment by serup** [comment]
well the scroll bar does not take events from trying to move it with mouse - is it supposed to work with mouse?

**Comment by lornix** [comment]
Not that I'm aware of.  You can scroll your document with the mouse if you're using the GUI version of vim, or with the use of the 'mouse+=a' option in the text version of vim.

**Comment by samliu** [comment]
lornix +1

Sorry, the plugin doesn't support mouse at this time. If you want to use mouse I'd recommend gvim/macvim, where a scrollbar is already provided.
